version: "3.9"

services:
  bot:
    profiles: [ "bot" ]
    build:
      context: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "-Om", "src.bot"]
    env_file:
      - .env

  api:
    profiles: [ "api" ]
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.server.main:app --reload --host 0.0.0.0 --port 80
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8000/docs" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    env_file:
      - .env

  postgres:
    profiles: [ "api", "bot", "observer" ]
    image: "postgres:16-alpine"
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USER
      POSTGRES_DB: $DATABASE
    volumes:
      - user_service.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  user_service.postgres.data: {}
